1.	Create a python program to find duplicate files by content. <br>
User will input path and it will scan all directories & sub-directories to find all duplicates files. <br>
Delete the found duplicate file. <br>
[Hint: use hashlib]


In [46]:
import os
import hashlib

In [47]:
path = input("Enter path of the first file: ")
dirList = os.listdir(path)

Enter path of the first file: C:\Training Material


In [48]:
hashList = []
duplicate = []
pathDirDict = {path : dirList}

In [49]:
for i in dirList:
    if '.' not in i:
        pathDirDict[path + '\\' + i] = os.listdir(path + '\\' + i)

In [50]:
'file1.txt' in pathDirDict['C:\\Training Material']

True

In [51]:
pathDirDict['C:\\Training Material']

['27feb Python TEK - Functions _ Misc..ipynb',
 '28feb Python - Error & Exception Handling.ipynb',
 '28feb Python TEK - OOP & File Handling.ipynb',
 '2March Pandas TEK.ipynb',
 '2March Python TEK - File Handling & Errors Execptions.ipynb',
 '2_March_assignment_II.docx',
 '3 March SQL-TEK.docx.pdf',
 'Automobile_price_data__Raw_.csv',
 'Day Wise Plan - Data Engineering.xlsx',
 'File Handling.pdf',
 'file1.txt',
 'file2.txt',
 'file3.txt',
 'New folder',
 'OOPs Concepts with Python.pdf',
 'Python Programming.pdf',
 'Python TEK I .ipynb',
 'Python TEK II.ipynb',
 'Question Given.docx',
 'Tek test.ipynb']

In [52]:
for i in pathDirDict:
    for j in pathDirDict[i]:
        if '.txt' in j:
            fileObj = open(i + '\\' + j)
            str1 = fileObj.read().encode()
            hash1 = hashlib.sha256(str1)
            if hash1.hexdigest() in hashList:
                duplicate.append(i + '\\' + j)
            else:
                hashList.append(hash1.hexdigest())
            fileObj.close()

In [53]:
for path in duplicate:
    print(os.remove(path, dir_fd=None))

None
None


2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters. 
    Using these packages [random, strings]


In [16]:
import random
import string

def generate_password():
    char_list = []
    char_list.append(random.choice(string.ascii_uppercase))
    for i in range(2):
        char_list.append(random.choice(string.ascii_lowercase))
    for i in range(2):
        char_list.append(random.choice(string.digits))
    char_list.append(random.choice(string.punctuation))

    random.shuffle(char_list)

    empty = ""
    password = empty.join(char_list)
    
    return password

print(generate_password())

2%Kng3


3. Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [18]:
import numpy as np

rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))
size = rows * cols

array = np.arange(size).reshape(rows, cols)
print(array)

Enter the number of rows: 5
Enter the number of columns: 5
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [19]:
n = size
prime_list = [2]
for i in range(3, n):
    if i%2 != 0:
        flag = True
        for j in range(3, int(i/2)):
            
            if i%j == 0:
                flag = False
                break
        if flag == True:
            prime_list.append(i)
print(prime_list)

[2, 3, 5, 7, 11, 13, 17, 19, 23]


In [20]:
for i in prime_list:
    row = i // cols
    col = i % cols
    
    array[row][col] = i ** 3
print(array)

[[    0     1     8    27     4]
 [  125     6   343     8     9]
 [   10  1331    12  2197    14]
 [   15    16  4913    18  6859]
 [   20    21    22 12167    24]]


4. Python program to get the sum of every cubed value and its previous integer.

In [21]:
import copy as cp
array_copy = cp.copy(array)
for i in prime_list:
    row = i // cols
    col = i % cols
    if col == 0: # If index is the first position in any row
        prev_row = row - 1 # go back to previous row
        prev_col = cols - 1 # to the last column
        array[row][col] += array_copy[prev_row][prev_col]
    else:
        prev_row = row
        prev_col = col - 1
        array[row][col] += array_copy[prev_row][prev_col]
print(array)

[[    0     1     9    35     4]
 [  129     6   349     8     9]
 [   10  1341    12  2209    14]
 [   15    16  4929    18  6877]
 [   20    21    22 12189    24]]


5.	Given two arrays, find their intersection. Examples:

    Input:  arr1[] = [1, 3, 4, 5, 7], arr2[] = [2, 3, 5, 6]


In [6]:
arr1 = [1, 3, 4, 5, 7]
arr2 = [2, 3, 5, 6]
list[set(arr1) & set(arr2)]

list[{3, 5}]

In [7]:
[x for x in arr1 if x in arr2]

[3, 5]

In [8]:
set(arr1).intersection(arr2)

{3, 5}

In [11]:
list(filter(lambda x : x in arr1, arr2))

[3, 5]

In [13]:
def intersection(lst1, lst2):
    final_lst = []
    for i in lst1:
        if i in lst2:
            final_lst.append(i)
    return final_lst

print(intersection(arr1, arr2))

[3, 5]


6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [29]:
seven_array = np.zeros((7,7), dtype = 'int')
count = 1
for i in range(7):
    for j in range(7):
        seven_array[i][j] = 7 * count
        count += 1
print(seven_array)
print("\nLast element is", seven_array[6, 6])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]

Last element is 343


7.	Checker Board Patten using Numpy

1 0 1 0 1 0 1 <br>
0 1 0 1 0 1 0 <br>
1 0 1 0 1 0 1 <br>
0 1 0 1 0 1 0 <br>
1 0 1 0 1 0 1

In [33]:
cb_rows = int(input("Enter number of rows: "))
cb_columns = int(input("Enter number of columns: "))
board = np.zeros((cb_rows, cb_columns), dtype = 'int')
for i in range(cb_rows):
    for j in range(cb_columns):
        if (i + j) % 2 == 0:
            board[i][j] = 1
print(board)

Enter number of rows: 5
Enter number of columns: 7
[[1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]


8.	Create the given Matrix

A B C D <br>
E F G H <br>
I a K L <br>
M N o P <br>
Q R S T <br>
U 0 W O

Replace all the vowels by np.nan <br>
A, E, I, O U  -- >  np.nan <br>
Return the count of the missing values

In [37]:
custom_array = np.array([['A', 'B', 'C', 'D'], ['E', 'F', 'G', 'H'], 
                        ['I', 'a', 'K', 'L'], ['M', 'N', 'o', 'P'], 
                        ['Q', 'R', 'S', 'T'], ['U', 0, 'W', 'O'] ])
print(custom_array)
vowels = ['A', 'E', 'I', 'O', 'U', 'a', 'e', 'i', 'o', 'u']
nan_count = 0
for i in range(6):
    for j in range(4):
        if custom_array[i][j] in vowels:
            custom_array[i][j] = np.nan
            nan_count += 1
print("")
print(custom_array)
print("\nNumber of missing values are", nan_count)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']
 ['I' 'a' 'K' 'L']
 ['M' 'N' 'o' 'P']
 ['Q' 'R' 'S' 'T']
 ['U' '0' 'W' 'O']]

[['nan' 'B' 'C' 'D']
 ['nan' 'F' 'G' 'H']
 ['nan' 'nan' 'K' 'L']
 ['M' 'N' 'nan' 'P']
 ['Q' 'R' 'S' 'T']
 ['nan' '0' 'W' 'nan']]

Number of missing values are 7
